export enum LoggingKind {
  LOGKIND_INFO      = "LOGKIND_INFO",
  LOGKIND_WARNING   = "LOGKIND_WARNING",
  LOGKIND_ERROR     = "LOGKIND_ERROR",
  LOGKIND_CRITICAL  = "LOGKIND_CRITICAL",
  LOGKIND_DEBUG     = "LOGKIND_DEBUG",
  LOGKIND_TRACE     = "LOGKIND_TRACE"
};